// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "adaptive-container": {
      name: "adaptive-container",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/adaptive-container.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/adaptive-container.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "rating": {
      name: "rating",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/rating.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/rating.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating": {
      name: "face-rating",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/face-rating.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/face-rating.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "star-rating": {
      name: "star-rating",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/star-rating.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/star-rating.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "upvote-downvote-rating": {
      name: "upvote-downvote-rating",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/upvote-downvote-rating.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/upvote-downvote-rating.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector": {
      name: "variant-selector",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/variant-selector.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/variant-selector.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-color": {
      name: "variant-selector-color",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/variant-selector-color.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/variant-selector-color.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "adaptive-container-demo": {
      name: "adaptive-container-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["adaptive-container","button"],
      files: [{
        path: "registry/default/example/adaptive-container-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/adaptive-container-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "rating-demo": {
      name: "rating-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["rating"],
      files: [{
        path: "registry/default/example/rating-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/rating-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "rating-fraction": {
      name: "rating-fraction",
      description: "",
      type: "registry:example",
      registryDependencies: ["rating"],
      files: [{
        path: "registry/default/example/rating-fraction.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/rating-fraction.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "rating-max-rating": {
      name: "rating-max-rating",
      description: "",
      type: "registry:example",
      registryDependencies: ["rating"],
      files: [{
        path: "registry/default/example/rating-max-rating.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/rating-max-rating.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "rating-custom-colors": {
      name: "rating-custom-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["rating"],
      files: [{
        path: "registry/default/example/rating-custom-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/rating-custom-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "star-rating-demo": {
      name: "star-rating-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["rating"],
      files: [{
        path: "registry/default/example/star-rating-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/star-rating-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "star-rating-custom-colors": {
      name: "star-rating-custom-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["rating"],
      files: [{
        path: "registry/default/example/star-rating-custom-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/star-rating-custom-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating-demo": {
      name: "face-rating-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/face-rating-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/face-rating-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating-custom-colors": {
      name: "face-rating-custom-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/face-rating-custom-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/face-rating-custom-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating-base-color": {
      name: "face-rating-base-color",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/face-rating-base-color.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/face-rating-base-color.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating-sizes": {
      name: "face-rating-sizes",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/face-rating-sizes.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/face-rating-sizes.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating-controlled": {
      name: "face-rating-controlled",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/face-rating-controlled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/face-rating-controlled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "face-rating-read-only": {
      name: "face-rating-read-only",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/face-rating-read-only.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/face-rating-read-only.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "upvote-downvote-rating-demo": {
      name: "upvote-downvote-rating-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/upvote-downvote-rating-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/upvote-downvote-rating-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "upvote-downvote-rating-custom-colors": {
      name: "upvote-downvote-rating-custom-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/upvote-downvote-rating-custom-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/upvote-downvote-rating-custom-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "upvote-downvote-rating-abbreviation": {
      name: "upvote-downvote-rating-abbreviation",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/upvote-downvote-rating-abbreviation.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/upvote-downvote-rating-abbreviation.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "upvote-downvote-rating-controlled": {
      name: "upvote-downvote-rating-controlled",
      description: "",
      type: "registry:example",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/example/upvote-downvote-rating-controlled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/upvote-downvote-rating-controlled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-demo": {
      name: "variant-selector-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector"],
      files: [{
        path: "registry/default/example/variant-selector-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-controlled": {
      name: "variant-selector-controlled",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector"],
      files: [{
        path: "registry/default/example/variant-selector-controlled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-controlled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-custom-colors": {
      name: "variant-selector-custom-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector"],
      files: [{
        path: "registry/default/example/variant-selector-custom-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-custom-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-images": {
      name: "variant-selector-images",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector"],
      files: [{
        path: "registry/default/example/variant-selector-images.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-images.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-colors": {
      name: "variant-selector-colors",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector"],
      files: [{
        path: "registry/default/example/variant-selector-colors.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-colors.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-color-demo": {
      name: "variant-selector-color-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector-color"],
      files: [{
        path: "registry/default/example/variant-selector-color-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-color-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-color-with-labels": {
      name: "variant-selector-color-with-labels",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector-color"],
      files: [{
        path: "registry/default/example/variant-selector-color-with-labels.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-color-with-labels.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-color-controlled": {
      name: "variant-selector-color-controlled",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector-color"],
      files: [{
        path: "registry/default/example/variant-selector-color-controlled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-color-controlled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "variant-selector-color-custom-styles": {
      name: "variant-selector-color-custom-styles",
      description: "",
      type: "registry:example",
      registryDependencies: ["variant-selector-color"],
      files: [{
        path: "registry/default/example/variant-selector-color-custom-styles.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/variant-selector-color-custom-styles.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "rating-block": {
      name: "rating-block",
      description: "",
      type: "registry:exampleBlock",
      registryDependencies: ["face-rating"],
      files: [{
        path: "registry/default/exampleBlock/rating-block.tsx",
        type: "registry:exampleBlock",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/exampleBlock/rating-block.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "context": {
      name: "context",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/context.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/context.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
